### ISSUE TITLE
Does not compile on kernel >=5.15-rc1

### ISSUE THREAD

**Issue by All3xJ** [aymanbagabas/Huawei-WMI#58]
I downloaded huawei-wmi-3.4-source-only.dkms.tar.gz release and then
```
sudo dkms ldtarball --archive=huawei-wmi-3.4-source-only.dkms.tar.gz
sudo dkms autoinstall -m huawei-wmi/3.4 # fails
```
In the logs cat /var/lib/dkms/rtl88x2bu/5.6.1/build/make.log:
```
/usr/src/rtl88x2bu-5.6.1/core/rtw_br_ext.c:20:18: fatal error: net/ipx.h: No such file or directory
   20 |         #include <net/ipx.h>
      |                  ^~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:287: /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_br_ext.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1846: /var/lib/dkms/rtl88x2bu/5.6.1/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.16.15-arch1-1/build'
make: *** [Makefile:2284: modules] Error 2
```

This is due to kernel commit 6c9b40844751 ("net: Remove net/ipx.h and uapi/linux/ipx.h header files"), merged in v5.15-rc1

**Comment by egormanga** [comment]
Just to clarify: am I right seeing you posting about [`rtl88x2bu`](https://github.com/cilynx/rtl88x2bu) build errors on the `huawei-wmi` repo?

Anyway, let's see (`man dkms`):
```
ACTIONS
       ...

       autoinstall

           Attempt to install the latest revision of  all  modules  that  have
           been installed for other kernel revisions. ...
```

> to install ... **all** modules

See?

You're supposed to use plain `install` command (or rather not complain about other modules' build failures on a batch build).

P.S. Yes, the comments in the readme [section](https://github.com/aymanbagabas/Huawei-WMI#use-dkms-tarball-installation) are incorrect too, but it's always a good thing to be observant and critical nonetheless. You have missed both noticing the wrong dkms module in the output **and** reading the man first, which helps in most cases. This could've been a nice doc-fixing PR instead then :)

No offense tho, this is a fine issue otherwise — just belonging elsewhere but here. (And please, remember to strip out the `huawei-wmi` mentions when you post it to the right place!)
